version: 2

updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "gabrielalejandrogomez"
    assignees:
      - "gabrielalejandrogomez"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
    # Group minor and patch updates
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "zod"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastify"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "gabrielalejandrogomez"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci"
      - "automated"

